export const MODE_LIGHT = "light";
export const MODE_DARK = "dark";
export const THEME_DIR = "ltr";
export const THEME_LOCALE = "en";
export const THEME_CURRENCY = "USD";
export const THEME_COUNTRY = "US";
export const SIDE_NAV_WIDTH = 290;
export const SIDE_NAV_COLLAPSED_WIDTH = 80;
export const SIDE_NAV_CONTENT_GUTTER = "px-2";
export const LOGO_X_GUTTER = "px-6";
export const HEADER_HEIGHT = 88;
export const PAGE_CONTAINER_GUTTER_X = "px-4 sm:px-6 md:px-8";
export const PAGE_CONTAINER_GUTTER_Y = "py-4 sm:py-6 md:px-8";

export const LAYOUT_DEFAULT = "default";
export const LAYOUT_PRO = "pro";
export const LAYOUT_BLANK = "blank";

export const THEME_ENUM = {
  MODE_LIGHT: MODE_LIGHT,
  MODE_DARK: MODE_DARK,
  SIDE_NAV_WIDTH: SIDE_NAV_WIDTH,
  SIDE_NAV_COLLAPSED_WIDTH: SIDE_NAV_COLLAPSED_WIDTH,
  HEADER_HEIGHT: HEADER_HEIGHT,
  THEME_DIR: THEME_DIR,
  THEME_LOCALE: THEME_LOCALE,
  THEME_CURRENCY: THEME_CURRENCY,
  THEME_COUNTRY: THEME_COUNTRY,
  SIDE_NAV_CONTENT_GUTTER: SIDE_NAV_CONTENT_GUTTER,
  LOGO_X_GUTTER: LOGO_X_GUTTER,
  PAGE_CONTAINER_GUTTER_X: PAGE_CONTAINER_GUTTER_X,
  PAGE_CONTAINER_GUTTER_Y: PAGE_CONTAINER_GUTTER_Y,
  LAYOUT_DEFAULT: LAYOUT_DEFAULT,
  LAYOUT_PRO: LAYOUT_PRO,
  LAYOUT_BLANK: LAYOUT_BLANK,
} as const;
